[package]
name = "veda-ft-indexer"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.6"
log = "0.4"
rust-ini = "0.13"
xapian-rusty = "0.0.29"
#xapian-rusty = { path = "../xapian-rusty" }
maplit = "1.0.2"
crc32fast = "1.2"
scan_fmt = "0.1.3"

v_queue = { path = "../v-queue" }
v_onto = { path = "../v-onto" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
v_search = { path = "../v-search" }
