dist: trusty
sudo: required

language: node_js
node_js: "stable"

before_install:
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - stty cols 80
  - sudo apt-get install cargo
  - sudo apt-get install curl
  - sudo apt-get install nodejs-legacy
  - ./control-install.sh&>install.log    
  - dub -v fetch vibe-d --version=0.7.30

addons:
#  firefox: latest
#  sauce_connect:
#    username: semanticmachines
#    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

# Build
install:
#  - npm install --save-dev testcafe-browser-provider-saucelabs
  - npm install --save-dev testcafe
  - go version
  - ./build.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 60
  - fluxbox >/dev/null 2>&1 &
  - ./control-start.sh

after_script:
  - ./control-stop.sh

after_failure:
  - ./control-stop.sh
  - ./send-to-chunk-io.sh