dist: xenial
sudo: required

language: java

before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install -y git

jobs:
  include:
    - stage: build
      script:
        - ./travis-tools/build.sh
        - ./travis-tools/git-push.sh
    - stage: test
      script:
        - ./travis-tools/git-pull.sh
        - echo "TESTING"
        - ./travis-tools/git-clear.sh
