dist: xenial
sudo: required

services:
  - xvfb

language: node_js
node_js: "stable"

addons:
    chrome: stable

before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install dpkg
  - sudo apt-get install -y xvfb
  - stty cols 80
  - sudo apt-get install nodejs-legacy
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt --save-dev

# Build
install:
  - ./tools/install-tarantool.sh
  - ./tools/install-clickhouse.sh
  - ./control-install.sh
#&>install.log
#  - ./tools/send-to-chunk-io.sh
  - source $HOME/.cargo/env
  - npm install --save-dev testcafe
  - go version
  - dmd --version
  - rustc -V
  - ./build.sh

before_script:
  - "export DISPLAY=:99.0"
  - fluxbox >/dev/null 2>&1 &
  - "cp -R ./qa/onto/* ./ontology 2>/dev/null || :"
  - ./control-start.sh
  - sleep 180

script:
  - travis_wait 3 grunt test --stack --verbose
  - travis_wait 6 testcafe chrome qa/testcafe/testLogin.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testLanguage.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testPerson.js --screenshots screens --screenshots-on-fails screens --speed 0.7
  - travis_wait 6 testcafe chrome qa/testcafe/testSearch.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testAttributiveSearch.js --screenshots screens --screenshots-on-fails screens --speed 0.7
  - travis_wait 6 testcafe chrome qa/testcafe/testCreatingNetInterface.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testDeleteAndRecovery.js --screenshots screens --screenshots-on-fails screens --speed 0.7
  - travis_wait 6 testcafe chrome qa/testcafe/testJournal.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testRights.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testSearchRangeOfDates.js --screenshots screens --screenshots-on-fails screens --speed 0.8
#  - testcafe chrome qa/testcafe/testVersionedDocument.js
  - travis_wait 6 testcafe chrome qa/testcafe/testSimpleNet.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testSimpleNet2.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testSimpleNet3.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testSimpleNetLowPriority.js --screenshots screens --screenshots-on-fails screens --speed 0.8
  - travis_wait 6 testcafe chrome qa/testcafe/testControls.js --screenshots screens --screenshots-on-fails screens --speed 0.8
#  - testcafe chrome qa/testcafe/testDrafts.js
  - travis_wait 10 testcafe chrome qa/testcafe/testDropDown.js --screenshots screens --screenshots-on-fails screens --speed 0.7
  - travis_wait 6 testcafe chrome qa/testcafe/testComment.js --screenshots screens --screenshots-on-fails screens --speed 0.7

after_script:
  - ./control-stop.sh

after_failure:
  - ./control-stop.sh
  - ./tools/send-to-chunk-io.sh
