[package]
name = "veda-ft-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.6"
log = "0.4"
rust-ini = "0.13"
nng = "0.5.1"
serde_json = "1.0"
serde = "1.0"
url = "2.1.1"

v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
v_search = { path = "../v-search" }
v_ft_xapian = { path = "../v-ft-xapian" }
v_storage = { path = "../v-storage" }

