[package]
name = "v_exim"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[lib]
path = "src/exim.rs"

[dependencies]
env_logger = "0.6"
log = "0.4"
enum-primitive-derive = "0.1"
num-traits = "0.1"
v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }
