version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Install"
          command: | 
           sudo apt-get clean
           sudo apt-get update
           sudo apt-get install dpkg
           ./tools/install-tarantool.sh
           ./tools/install-clickhouse.sh
           ./control-install.sh
           source $HOME/.cargo/env
           go version
           rustc -V

  test:
    docker:
      - image: circleci/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build