[package]
name = "veda-search-index-pt"
version = "0.1.0"
authors = ["Roman Karpov <roman.karpov@gmail.com>"]
edition = "2018"

[dependencies]
clickhouse-rs = "0.2.0-alpha.4"
futures = "0.3.1"
tokio = { version = "0.2.10", features = ["full"] }
log = "0.4"
chrono = "0.4.9"
chrono-tz = "0.5"
lazy_static = "1.4.0"
regex = "1"
url = "2.1.1"

v_queue = { path = "../v-queue" }
v_search = { path = "../v-search" }
v_onto = { path = "../v-onto" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
