[package]
name = "veda-camunda-connector"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camunda-client = "0.1.0"
log = "0.4"

v_api = { path = "../v-api" }
v_module = { path = "../v-module" }
v_storage = { path = "../v-storage" }
v_onto = { path = "../v-onto" }
v_queue = { path = "../v-queue" }
