[package]
name = "veda-ontologist"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-ontologist"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
serde_json = "1.0"
bincode = "1.2.1"
serde_derive = "1.0.104"
serde = "1.0.104"
env_logger = "0.6"
log = "0.4"
rust-ini = "0.15"
quote = "1.0.3"

v_queue = { path = "../v-queue" }
v_onto = { path = "../v-onto" }
v_ft_xapian = { path = "../v-ft-xapian" }
v_search = { path = "../v-search" }
v_storage = { path = "../v-storage" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
