[package]
name = "veda-input-onto"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-input-onto"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
env_logger = "0.6"
scan_fmt = "0.2"
log = "0.4"
rust-ini = "0.13"
rio_turtle = {git="https://github.com/semantic-machines/rio.git", rev="857dc9657021cd6e4092b77c889b28eecfac7eb6"}
rio_api = "0.3.1"
notify = "=5.0.0-pre.1"
crossbeam-channel = "0.3.9"
v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }

